### PR TITLE
minor changes to libs and readme

### PR DESCRIPTION
**Pull request by gretel**
cosmetics
fix docs
add doc header for refresh

### CODE REVIEW

**Comment by bucaran** [comment]
Hey @gretel thanks as usual, but I think we don't `func_avail` since we can simply `function -q` to check whether the function is available or not. The function `available` is already being used by several plugins and `wa` itself (maybe), and as you already well documented it, it's used to check if a program exists, and therefore it can be run.

**Comment by gretel** [comment]
yea it's just a comfort wrapper.. i was in doubt too. what bothers me most is the breakage with what is using `available`. what do you think, just have `exec_avail` and name it `available` as before?

**Comment by bucaran** [comment]
Let's just keep the comments and avoid modifying the code for now.

**Comment by gretel** [comment]
but how to fix the breakage on freebsd then :smiling_imp:

**Comment by bucaran** [comment]
What do you mean? is `available` a freebsd function?

**Comment by gretel** [comment]
check https://github.com/wahoo-fish/wahoo/pull/47 please

**Comment by bucaran** [comment]
maybe just check if $OSNAME is freebsd and add explicit support for how freebsd works

**Comment by gretel** [comment]
the current implementation fails when having the `pyenv` and/or `direnv` plugin loaded but the according binaries not installed. my reference with freebsd is wrong, i justed noticed it there, because i had the packages installed, but not the binaries.

**Comment by bucaran** [comment]
What is wrong with

```fish
function available -a program -d "check if a program is available."
  type "$program" ^/dev/null >&2
end
```

**Pull request closed without merging**
